import java.util.Properties;

import javax.mail.*;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;


public class EmailReport {

    /** Recipient's email address */
    public static String email_address;

    /** Report to be sent via email. */
    public static StringBuilder report;

    /** Creates an individual email to send based
     on the report generated by StockReport. */
    public EmailReport(String email, StringBuilder report) {
        this.email_address = email;
        this.report = report;
    }
    public void Send() {
        /** Recipient's email ID needs to be mentioned. */
        String to = this.email_address;

        /** Sender's email ID needs to be mentioned */
        String from = "mohid.tanveer011@gmail.com";

        /** Assuming you are sending email from through gmail's smtp */
        String host = "smtp.gmail.com";

        /** Get system properties */
        Properties properties = System.getProperties();

        /** Setup mail server */
        properties.put("mail.smtp.host", host);
        properties.put("mail.smtp.port", "465");
        properties.put("mail.smtp.auth", "true");
        properties.put("mail.smtp.starttls.enable", "true");
        properties.put("mail.smtp.starttls.required", "true");
        properties.put("mail.smtp.ssl.protocols", "TLSv1.2");
        properties.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");

        /** Get the Session object.// and pass username and password */
        Session session = Session.getInstance(properties, new javax.mail.Authenticator() {

            protected PasswordAuthentication getPasswordAuthentication() {

                return new PasswordAuthentication("comp142daytrading@gmail.com", "12345678abcd*");

            }

        });

        try {
            /** Create a default MimeMessage object. */
            MimeMessage message = new MimeMessage(session);

            /** Set From: header field of the header. */
            message.setFrom(new InternetAddress(from));

            /** Set To: header field of the header. */
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));

            /** Set Subject: header field */
            message.setSubject("Stock Report");

            /** Now set the actual message */
            message.setText(this.report.toString());

            System.out.println("sending...");
            /** Send message */
            Transport.send(message);
            System.out.println("Sent message successfully....");
        } catch (MessagingException mex) {
            mex.printStackTrace();
        }

    }
}
